name: Deploy

on:
  push:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su -
            cd /var/www
            git status
            git reset --hard
            git pull origin prod
            cd /var/www/servers/chat
            node_modules/pm2/bin/pm2 stop chat-sugoi
            node_modules/pm2/bin/pm2 delete chat-sugoi
            node_modules/pm2/bin/pm2 start index.js --name="chat-sugoi"
            cd /var/www/servers/map
            node_modules/pm2/bin/pm2 stop map-sugoi
            node_modules/pm2/bin/pm2 delete map-sugoi
            node_modules/pm2/bin/pm2 start server.php --name="map-sugoi"
          
            
            
