name: Deploy

on:
  push:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su -
            cd /var/www
            git status
            git reset --hard
            git pull origin prod
            node_modules/pm2/bin/pm2 stop sugoi-chat
            node_modules/pm2/bin/pm2 delete sugoi-chat
            node_modules/pm2/bin/pm2 start /var/www/servers/chat/index.js --name="sugoi-chat"
            node_modules/pm2/bin/pm2 stop sugoi-map
            node_modules/pm2/bin/pm2 delete sugoi-map
            node_modules/pm2/bin/pm2 start /var/www/servers/map/server.php --name="sugoi-map"
